wandb_version: 1

_current_progress_remaining:
  desc: null
  value: 0.9190001
_custom_logger:
  desc: null
  value: 'False'
_episode_num:
  desc: null
  value: 0
_episode_storage:
  desc: null
  value: None
_last_episode_starts:
  desc: null
  value: '[ True]'
_last_obs:
  desc: null
  value: "[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.\n\
    \  0. 0.]]"
_last_original_obs:
  desc: null
  value: "[[ 80.718506  80.718506  79.0968    79.0968   143.24641  143.35359\n  143.24641\
    \  143.35359   80.937355  80.937355  78.87533   78.87533\n  143.2463   143.3537\
    \   143.2463   143.3537   -34.300995 -25.832357\n  -25.542345 -30.304518   0.\
    \         0.         0.         0.\n    0.         0.      ]]"
_logger:
  desc: null
  value: <stable_baselines3.common.logger.Logger object at 0x0000014195BB39A0>
_n_updates:
  desc: null
  value: 809899
_num_timesteps_at_start:
  desc: null
  value: 0
_stats_window_size:
  desc: null
  value: 100
_total_timesteps:
  desc: null
  value: 10000000
_vec_normalize_env:
  desc: null
  value: None
_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: huggingface
    huggingface_version: 4.22.1
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1712314002.327517
    t:
      1:
      - 1
      - 2
      - 3
      - 11
      - 49
      - 55
      2:
      - 1
      - 2
      - 3
      - 11
      - 49
      - 55
      3:
      - 1
      - 3
      - 22
      - 23
      - 34
      4: 3.9.13
      5: 0.14.0
      6: 4.22.1
      8:
      - 1
      - 3
      - 5
action_noise:
  desc: null
  value: None
action_space:
  desc: null
  value: Box(-100.0, 100.0, (10,), float32)
actor:
  desc: null
  value: "Actor(\n  (features_extractor): FlattenExtractor(\n    (flatten): Flatten(start_dim=1,\
    \ end_dim=-1)\n  )\n  (latent_pi): Sequential(\n    (0): Linear(in_features=26,\
    \ out_features=64, bias=True)\n    (1): ReLU()\n    (2): Linear(in_features=64,\
    \ out_features=64, bias=True)\n    (3): ReLU()\n  )\n  (mu): Linear(in_features=64,\
    \ out_features=10, bias=True)\n  (log_std): Linear(in_features=64, out_features=10,\
    \ bias=True)\n)"
algo:
  desc: null
  value: SAC
batch_norm_stats:
  desc: null
  value: '[]'
batch_norm_stats_target:
  desc: null
  value: '[]'
batch_size:
  desc: null
  value: 256
buffer_size:
  desc: null
  value: 1000000
critic:
  desc: null
  value: "ContinuousCritic(\n  (features_extractor): FlattenExtractor(\n    (flatten):\
    \ Flatten(start_dim=1, end_dim=-1)\n  )\n  (qf0): Sequential(\n    (0): Linear(in_features=36,\
    \ out_features=256, bias=True)\n    (1): ReLU()\n    (2): Linear(in_features=256,\
    \ out_features=256, bias=True)\n    (3): ReLU()\n    (4): Linear(in_features=256,\
    \ out_features=1, bias=True)\n  )\n  (qf1): Sequential(\n    (0): Linear(in_features=36,\
    \ out_features=256, bias=True)\n    (1): ReLU()\n    (2): Linear(in_features=256,\
    \ out_features=256, bias=True)\n    (3): ReLU()\n    (4): Linear(in_features=256,\
    \ out_features=1, bias=True)\n  )\n)"
critic_target:
  desc: null
  value: "ContinuousCritic(\n  (features_extractor): FlattenExtractor(\n    (flatten):\
    \ Flatten(start_dim=1, end_dim=-1)\n  )\n  (qf0): Sequential(\n    (0): Linear(in_features=36,\
    \ out_features=256, bias=True)\n    (1): ReLU()\n    (2): Linear(in_features=256,\
    \ out_features=256, bias=True)\n    (3): ReLU()\n    (4): Linear(in_features=256,\
    \ out_features=1, bias=True)\n  )\n  (qf1): Sequential(\n    (0): Linear(in_features=36,\
    \ out_features=256, bias=True)\n    (1): ReLU()\n    (2): Linear(in_features=256,\
    \ out_features=256, bias=True)\n    (3): ReLU()\n    (4): Linear(in_features=256,\
    \ out_features=1, bias=True)\n  )\n)"
device:
  desc: null
  value: cuda
ent_coef:
  desc: null
  value: auto
ent_coef_optimizer:
  desc: null
  value: "Adam (\nParameter Group 0\n    amsgrad: False\n    betas: (0.9, 0.999)\n\
    \    capturable: False\n    differentiable: False\n    eps: 1e-08\n    foreach:\
    \ None\n    fused: None\n    lr: 0.0009190001\n    maximize: False\n    weight_decay:\
    \ 0\n)"
env:
  desc: null
  value: <stable_baselines3.common.vec_env.dummy_vec_env.DummyVecEnv object at 0x000001420C60EA90>
ep_info_buffer:
  desc: null
  value: deque([], maxlen=100)
ep_success_buffer:
  desc: null
  value: deque([], maxlen=100)
gamma:
  desc: null
  value: 0.99
gradient_steps:
  desc: null
  value: 1
learning_rate:
  desc: null
  value: <function linear_schedule.<locals>.func at 0x0000014184BDB670>
learning_starts:
  desc: null
  value: 100
log_ent_coef:
  desc: null
  value: tensor([-4.4609], device='cuda:0', requires_grad=True)
lr_schedule:
  desc: null
  value: <function linear_schedule.<locals>.func at 0x0000014184BDB670>
n_envs:
  desc: null
  value: 1
num_timesteps:
  desc: null
  value: 0
observation_space:
  desc: null
  value: "Box([ 70.64  70.64  70.64  70.64 136.8  136.8  136.8  136.8   70.64  70.64\n\
    \  70.64  70.64 136.8  136.8  136.8  136.8  -45.   -45.   -45.   -45.\n -45. \
    \  -45.   -45.   -45.   -45.   -45.  ], [ 84.14  84.14  84.14  84.14 148.8  148.8\
    \  148.8  148.8   84.14  84.14\n  84.14  84.14 148.8  148.8  148.8  148.8   45.\
    \    45.    45.    45.\n  45.    45.    45.    45.    45.    45.  ], (26,), float32)"
optimize_memory_usage:
  desc: null
  value: 'False'
policy:
  desc: null
  value: "SACPolicy(\n  (actor): Actor(\n    (features_extractor): FlattenExtractor(\n\
    \      (flatten): Flatten(start_dim=1, end_dim=-1)\n    )\n    (latent_pi): Sequential(\n\
    \      (0): Linear(in_features=26, out_features=64, bias=True)\n      (1): ReLU()\n\
    \      (2): Linear(in_features=64, out_features=64, bias=True)\n      (3): ReLU()\n\
    \    )\n    (mu): Linear(in_features=64, out_features=10, bias=True)\n    (log_std):\
    \ Linear(in_features=64, out_features=10, bias=True)\n  )\n  (critic): ContinuousCritic(\n\
    \    (features_extractor): FlattenExtractor(\n      (flatten): Flatten(start_dim=1,\
    \ end_dim=-1)\n    )\n    (qf0): Sequential(\n      (0): Linear(in_features=36,\
    \ out_features=256, bias=True)\n      (1): ReLU()\n      (2): Linear(in_features=256,\
    \ out_features=256, bias=True)\n      (3): ReLU()\n      (4): Linear(in_features=256,\
    \ out_features=1, bias=True)\n    )\n    (qf1): Sequential(\n      (0): Linear(in_features=36,\
    \ out_features=256, bias=True)\n      (1): ReLU()\n      (2): Linear(in_features=256,\
    \ out_features=256, bias=True)\n      (3): ReLU()\n      (4): Linear(in_features=256,\
    \ out_features=1, bias=True)\n    )\n  )\n  (critic_target): ContinuousCritic(\n\
    \    (features_extractor): FlattenExtractor(\n      (flatten): Flatten(start_dim=1,\
    \ end_dim=-1)\n    )\n    (qf0): Sequential(\n      (0): Linear(in_features=36,\
    \ out_features=256, bias=True)\n      (1): ReLU()\n      (2): Linear(in_features=256,\
    \ out_features=256, bias=True)\n      (3): ReLU()\n      (4): Linear(in_features=256,\
    \ out_features=1, bias=True)\n    )\n    (qf1): Sequential(\n      (0): Linear(in_features=36,\
    \ out_features=256, bias=True)\n      (1): ReLU()\n      (2): Linear(in_features=256,\
    \ out_features=256, bias=True)\n      (3): ReLU()\n      (4): Linear(in_features=256,\
    \ out_features=1, bias=True)\n    )\n  )\n)"
policy_class:
  desc: null
  value: <class 'stable_baselines3.sac.policies.SACPolicy'>
policy_kwargs:
  desc: null
  value: '{''net_arch'': {''pi'': [64, 64], ''qf'': [256, 256]}, ''use_sde'': False}'
replay_buffer:
  desc: null
  value: <stable_baselines3.common.buffers.ReplayBuffer object at 0x000001419E3A6F70>
replay_buffer_class:
  desc: null
  value: <class 'stable_baselines3.common.buffers.ReplayBuffer'>
replay_buffer_kwargs:
  desc: null
  value: '{}'
sde_sample_freq:
  desc: null
  value: -1
seed:
  desc: null
  value: None
start_time:
  desc: null
  value: 1712314009599580000
target_entropy:
  desc: null
  value: -10.0
target_update_interval:
  desc: null
  value: 1
tau:
  desc: null
  value: 0.005
tensorboard_log:
  desc: null
  value: 5gdl/
train_freq:
  desc: null
  value: 'TrainFreq(frequency=1, unit=<TrainFrequencyUnit.STEP: ''step''>)'
use_sde:
  desc: null
  value: 'False'
use_sde_at_warmup:
  desc: null
  value: 'False'
verbose:
  desc: null
  value: 1
