wandb_version: 1

_current_progress_remaining:
  desc: null
  value: 0.9054546666666666
_custom_logger:
  desc: null
  value: 'False'
_episode_num:
  desc: null
  value: 0
_episode_storage:
  desc: null
  value: None
_last_episode_starts:
  desc: null
  value: '[ True]'
_last_obs:
  desc: null
  value: '[[ 2.3715582   7.86519     0.09772919 -0.20245737  0.          0.        ]]'
_last_origina