wandb_version: 1

_current_progress_remaining:
  desc: null
  value: 1.0
_custom_logger:
  desc: null
  value: 'False'
_episode_num:
  desc: null
  value: 0
_last_episode_starts:
  desc: null
  value: '[ True]'
_last_obs:
  desc: null
  value: '[[0. 0. 0. 0. 0. 0.]]'
_last_original_obs:
  desc: null
  value: None
_logger:
  desc: null
  value: <stable_baselines3.common.logger.Logger object at 0x000001FDB2819280>
_n_updates:
  desc: null
  value: 0
_num_timesteps_at_start:
  desc: null
  value: 0
_stats_window_size:
  desc: null
  value: 100
_total_timesteps:
  desc: null
  value: 10000000
_vec_normalize_env:
  desc: null
  value: None
_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: huggingface
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1707316290.875126
    t:
      1:
      - 1
      - 2
      - 3
      - 55
      2:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 49
      - 53
      - 55
      3:
      - 1
      - 3
      - 22
      - 23
      - 35
      4: 3.9.13
      5: 0.14.0
      8:
      - 1
      - 3
      - 5
action_noise:
  desc: null
  value: None
action_space:
  desc: null
  value: Box(-100.0, 100.0, (2,), float32)
algo:
  desc: null
  value: A2C
device:
  desc: null
  value: cuda
ent_coef:
  desc: null
  value: 0.0
env:
  desc: null
  value: <stable_baselines3.common.vec_env.dummy_vec_env.DummyVecEnv object at 0x000001FDB2837B50>
ep_info_buffer:
  desc: null
  value: deque([], maxlen=100)
ep_success_buffer:
  desc: null
  value: deque([], maxlen=100)
gae_lambda:
  desc: null
  value: 1.0
gamma:
  desc: null
  value: 0.99
learning_rate:
  desc: null
  value: <function linear_schedule.<locals>.func at 0x000001FDB015B550>
lr_schedule:
  desc: null
  value: <function linear_schedule.<locals>.func at 0x000001FDB015B550>
max_grad_norm:
  desc: null
  value: 0.5
n_envs:
  desc: null
  value: 1
n_steps:
  desc: null
  value: 5
normalize_advantage:
  desc: null
  value: 'False'
num_timesteps:
  desc: null
  value: 0
observation_space:
  desc: null
  value: Box([-10. -10. -10. -10. -45. -45.], [10. 10. 10. 10. 45. 45.], (6,), float32)
policy:
  desc: null
  value: "ActorCriticPolicy(\n  (features_extractor): FlattenExtractor(\n    (flatten):\
    \ Flatten(start_dim=1, end_dim=-1)\n  )\n  (pi_features_extractor): FlattenExtractor(\n\
    \    (flatten): Flatten(start_dim=1, end_dim=-1)\n  )\n  (vf_features_extractor):\
    \ FlattenExtractor(\n    (flatten): Flatten(start_dim=1, end_dim=-1)\n  )\n  (mlp_extractor):\
    \ MlpExtractor(\n    (policy_net): Sequential(\n      (0): Linear(in_features=6,\
    \ out_features=8, bias=True)\n      (1): Tanh()\n      (2): Linear(in_features=8,\
    \ out_features=8, bias=True)\n      (3): Tanh()\n    )\n    (value_net): Sequential(\n\
    \      (0): Linear(in_features=6, out_features=256, bias=True)\n      (1): Tanh()\n\
    \      (2): Linear(in_features=256, out_features=256, bias=True)\n      (3): Tanh()\n\
    \    )\n  )\n  (action_net): Linear(in_features=8, out_features=2, bias=True)\n\
    \  (value_net): Linear(in_features=256, out_features=1, bias=True)\n)"
policy_class:
  desc: null
  value: <class 'stable_baselines3.common.policies.ActorCriticPolicy'>
policy_kwargs:
  desc: null
  value: '{''net_arch'': {''pi'': [8, 8], ''vf'': [256, 256]}, ''optimizer_class'':
    <class ''torch.optim.rmsprop.RMSprop''>, ''optimizer_kwargs'': {''alpha'': 0.99,
    ''eps'': 1e-05, ''weight_decay'': 0}}'
rollout_buffer:
  desc: null
  value: <stable_baselines3.common.buffers.RolloutBuffer object at 0x000001FDB28378B0>
sde_sample_freq:
  desc: null
  value: -1
seed:
  desc: null
  value: None
start_time:
  desc: null
  value: 1707316467478739100
tensorboard_log:
  desc: null
  value: 2gdl/
use_sde:
  desc: null
  value: 'False'
verbose:
  desc: null
  value: 1
vf_coef:
  desc: null
  value: 0.5
