wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.13
    cli_version: 0.16.0
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1701800555.31233
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 1
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 23
      - 34
      4: 3.9.13
      5: 0.16.0
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
